### ISSUE TITLE
Feature request: Generate types for useQuery (apollo)

### ISSUE THREAD

**Issue by Ciantic** [cometkim/gatsby-plugin-typegen#61]
I know this is a stretch, if you are not using Apollo you probably don't want to do this.

I intend to do dynamic queries on runtime in addition of `useStaticQuery`, and Apollo seems like the only option at the moment, it has a similarily named hook `useQuery`.

However with Apollo the official suggestion is to write *the types by hand* like it's 2010: 
https://www.apollographql.com/docs/react/development-testing/static-typing/#typing-hooks

**Edit** Apparently apollo does provide some codegen, even though the docs resorts to writing them by hand.

The syntax is quiet similar so I wonder would it be possible to add a way to support Apollo's `useQuery` too.

Thanks for considering, I know this is not your problem.

**Comment by cometkim** [comment]
Hi, @Ciantic, thank you for suggesting.

I'm actually using codegen for both Apollo Client and Gatsby in the same product and there have been several approaches that use only codegen CLI.

In fact, the CLI has potential bugs when running with monorepo projects and many different configs variants as a single process. The solution is to split the configuration file and process and run them concurrently, but this will make the development process too heavy.

This project doesn't provide some abstraction of graphql-codegen, but more deeply integrate with Gatsby. So it focuses on Gatsby, it improves the experience of using Gatsby without adding IO/configuration overhead.

You can still use the CLI for Apollo Client, but it can now be achieved with a simple configuration for Apollo Client only. (that's why I mentioned it [here](https://github.com/cometkim/gatsby-plugin-typegen#disclaimer))

**Comment by cometkim** [comment]
Configuration example:

```yml
schema:
  - ./shared/graphql/schema/executable-schema.graphql
  - ./frontend/src/client-schema.graphql

generates:
  # https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces
  ./frontend/src/fragment-types.json:
    plugins:
      - fragment-matcher

  ./frontend/src/generated/client.tsx:
    documents:
      - ./frontend/src/documents/**/*.{graphql}
      - ./frontend/src/components/**/*.{ts,tsx,graphql}
      - ./frontend/src/pages/**/*.{ts,tsx}
      - '!./frontend/src/pages/test/index.tsx'
    plugins:
      - typescript
      - typescript-resolvers
      - typescript-operations
      - typescript-react-apollo
    config:
      # This makes codegen only works for Apollo's gql tag
      pluckConfig:
        modules:
          - name: @apollo/client
            identifier: gql
      contextType: ~/src/apollo-client#ApolloClientContext
      scalars:
        DateTime: string
        Duration: number
        CalendarDate: string
        ConstraintString: string
        ConstraintNumber: number
      reactApolloVersion: 3
      withComponent: false
      withHOC: false
      withHooks: true
      withMutationFn: true
      enumsAsTypes: true
      defaultMapper: Partial<{T}>
```
